export const COMICS_UPDATE_LIST = 'COMICS_UPDATE_LIST'
export const COMICS_UPDATE_COMIC = 'COMICS_UPDATE_COMIC'
export const COMICS_SET_FETCHING = 'COMICS_SET_FETCHING'
export const COMICS_UPDATE_LIST_OFFSET = 'COMICS_UPDATE_LIST_OFFSET'